services:
    siwapp_customer.listener.invoice_listener:
        class: Siwapp\CustomerBundle\EventListener\InvoiceListener
        tags:
            - { name: doctrine.event_listener, event: postPersist }
            - { name: doctrine.event_listener, event: postUpdate }
