language: php
sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - '5.5'
  - '5.6'
  - '7.0'

before_install:
  - phpenv config-rm xdebug.ini
  - composer self-update

install:
   - composer install
