language: php
sudo: false

cache:
    directories:
        - $HOME/.composer/cache

php:
    - '5.5'
    - '5.6'
    - '7.0'

before_install:
    - phpenv config-rm xdebug.ini
    - composer self-update
    - mysql -e 'create database symfony'

install:
    - composer install
    - php bin/console doctrine:schema:create
