services:
    siwapp_user.locale_listener:
        class: Siwapp\UserBundle\EventListener\LocaleListener
        arguments: ['%kernel.default_locale%']
        tags:
            - { name: kernel.event_subscriber }
    siwapp_user.user_locale_listener:
        class: Siwapp\UserBundle\EventListener\UserLocaleListener
        arguments: ['@session']
        tags:
            - { name: kernel.event_listener, event: security.interactive_login, method: onInteractiveLogin }
    siwapp_user.form.profile:
        class: Siwapp\UserBundle\Form\ProfileFormType
        tags:
            - { name: form.type, alias: siwapp_user_user_profile }
